# Generated by Django 5.2.17 on 2026-09-25 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('designation', models.CharField(max_length=150)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='faculty/profile/')),
                ('short_intro', models.TextField(blank=True, help_text='Short introduction shown on the profile card.')),
                ('about', models.TextField(blank=True, help_text='About section.')),
                ('location', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('students_trained', models.CharField(blank=True, help_text='Example: 700+', max_length=50)),
                ('teaching_approach', models.CharField(blank=True, help_text='Example: Learn → Try → Build → Improve', max_length=255)),
                ('quote', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=150)),
                ('field_of_study', models.CharField(max_length=200)),
                ('institution', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(blank=True, help_text='Example: Currently pursuing / Completed', max_length=100)),
                ('start_year', models.PositiveIntegerField(blank=True, null=True)),
                ('end_year', models.PositiveIntegerField(blank=True, null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='reviews.facultyprofile')),
            ],
            options={
                'ordering': ['display_order', '-end_year'],
            },
        ),
        migrations.CreateModel(
            name='FacultySkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='reviews.facultyprofile')),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
